-------------------------------------------------------------------------------------------------------------
--
-- WoWPrimeAdminPanel Version 3.x
-- WoWPrimeAdminPanel is a derivative of TrinityAdmin/MangAdmin.
--
-- Copyright (C) 2007 Free Software Foundation, Inc.
-- License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl-3.0.en.html>
-- This is free software: you are free to change and redistribute it.
-- There is NO WARRANTY, to the extent permitted by law.
--
-- You should have received a copy of the GNU General Public License
-- along with this program; if not, write to the Free Software
-- Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
--
-- Repository: https://github.com/kotin201901-ux/WoWPrimeAdminPanel
--
-------------------------------------------------------------------------------------------------------------

--Convention:
-- WoWPrimeAdminPanel:PrepareScript(*nameofbutton*                    , Locale["*tooltiplocalisation*"]         , function() *functionnameandparameters()* end)

function InitControls()
--[[GM Tab]]
  WoWPrimeAdminPanel:PrepareScript(ma_displaylevelbutton              , Locale["tt_DisplayAccountLvl"]          , function() WoWPrimeAdminPanelCommands.DisplayAccountLevel() end)
  WoWPrimeAdminPanel:PrepareScript(ma_gmonbutton                      , Locale["tt_GMOnButton"]                 , function() WoWPrimeAdminPanelCommands.ToggleGMMode("on") end)
  WoWPrimeAdminPanel:PrepareScript(ma_gmoffbutton                     , Locale["tt_GMOffButton"]                , function() WoWPrimeAdminPanelCommands.ToggleGMMode("off") end)
  WoWPrimeAdminPanel:PrepareScript(ma_flyonbutton                     , Locale["tt_FlyOnButton"]                , function() WoWPrimeAdminPanelCommands.ToggleFlyMode("on") end)
  WoWPrimeAdminPanel:PrepareScript(ma_flyoffbutton                    , Locale["tt_FlyOffButton"]               , function() WoWPrimeAdminPanelCommands.ToggleFlyMode("off") end)
  WoWPrimeAdminPanel:PrepareScript(ma_hoveronbutton                   , Locale["tt_SpectatorOnButton"]           , function() WoWPrimeAdminPanelCommands.ToggleSpectatorMode("on") end)
  WoWPrimeAdminPanel:PrepareScript(ma_hoveroffbutton                  , Locale["tt_SpectatorOffButton"]          , function() WoWPrimeAdminPanelCommands.ToggleSpectatorMode("off") end)
  WoWPrimeAdminPanel:PrepareScript(ma_whisperonbutton                 , Locale["tt_WhispOnButton"]              , function() WoWPrimeAdminPanelCommands.ToggleWhisper("on") end)
  WoWPrimeAdminPanel:PrepareScript(ma_whisperoffbutton                , Locale["tt_WhispOffButton"]             , function() WoWPrimeAdminPanelCommands.ToggleWhisper("off") end)
  WoWPrimeAdminPanel:PrepareScript(ma_invisibleonbutton               , Locale["tt_InvisOnButton"]              , function() WoWPrimeAdminPanelCommands.ToggleVisible("off") end)
  WoWPrimeAdminPanel:PrepareScript(ma_invisibleoffbutton              , Locale["tt_InvisOffButton"]             , function() WoWPrimeAdminPanelCommands.ToggleVisible("on") end)
  WoWPrimeAdminPanel:PrepareScript(ma_cheattaxionbutton               , Locale["tt_TaxiOnButton"]               , function() WoWPrimeAdminPanelCommands.ToggleCheatTaxi("on") end)
  WoWPrimeAdminPanel:PrepareScript(ma_cheattaxioffbutton              , Locale["tt_TaxiOffButton"]              , function() WoWPrimeAdminPanelCommands.ToggleCheatTaxi("off") end)
  WoWPrimeAdminPanel:PrepareScript(ma_instantkillbutton               , Locale["tt_instakill"]                  , function() WoWPrimeAdminPanelCommands.InstantKill() end)
  WoWPrimeAdminPanel:PrepareScript(ma_speedslider                     , Locale["tt_SpeedSlider"]                , {{"OnMouseUp", function() WoWPrimeAdminPanelCommands.SetSpeed() end},{"OnValueChanged", function() ma_speedsliderText:SetText("Speed: "..string.format("%.1f", ma_speedslider:GetValue())) end}})
  WoWPrimeAdminPanel:PrepareScript(ma_scaleslider                     , Locale["tt_ScaleSlider"]                , {{"OnMouseUp", function() WoWPrimeAdminPanelCommands.SetScale() end},{"OnValueChanged", function() ma_scalesliderText:SetText("Scale: "..string.format("%.1f", ma_scaleslider:GetValue())) end}})
  WoWPrimeAdminPanel:PrepareScript(ma_screenshotbutton                , Locale["tt_ScreenButton"]               , function() WoWPrimeAdminPanelCommands.Screenie() end)
  WoWPrimeAdminPanel:PrepareScript(ma_setjail_a_button                , Locale["tt_SetJail_A_Button"]           , function() WoWPrimeAdminPanelCommands.SetJail_A() end)
  WoWPrimeAdminPanel:PrepareScript(ma_setjail_h_button                , Locale["tt_SetJail_H_Button"]           , function() WoWPrimeAdminPanelCommands.SetJail_H() end)
  WoWPrimeAdminPanel:PrepareScript(ma_gridnaviaheadbutton             , Locale["tt_N"]                          , function() WoWPrimeAdminPanelCommands.GridNavigate(nil, nil); WoWPrimeAdminPanel.db.char.nextGridWay = "north" end)
  WoWPrimeAdminPanel:PrepareScript(ma_gridnavibackbutton              , Locale["tt_S"]                          , function() WoWPrimeAdminPanelCommands.GridNavigate(nil, nil); WoWPrimeAdminPanel.db.char.nextGridWay = "south" end)
  WoWPrimeAdminPanel:PrepareScript(ma_gridnavirightbutton             , Locale["tt_E"]                          , function() WoWPrimeAdminPanelCommands.GridNavigate(nil, nil); WoWPrimeAdminPanel.db.char.nextGridWay = "east" end)
  WoWPrimeAdminPanel:PrepareScript(ma_gridnavileftbutton              , Locale["tt_W"]                          , function() WoWPrimeAdminPanelCommands.GridNavigate(nil, nil); WoWPrimeAdminPanel.db.char.nextGridWay = "west" end)
  --WoWPrimeAdminPanel:PrepareScript(ma_chatonbutton                    , Locale["tt_chatonbutton"]               , function() WoWPrimeAdminPanelCommands.ToggleChat("on") end)
  --WoWPrimeAdminPanel:PrepareScript(ma_chatoffbutton                   , Locale["tt_chatoffbutton"]              , function() WoWPrimeAdminPanelCommands.ToggleChat("off") end)
  WoWPrimeAdminPanel:PrepareScript(ma_waterwalkonbutton               , Locale["tt_waterwalkonbutton"]          , function() WoWPrimeAdminPanelCommands.ToggleWaterwalk("on") end)
  WoWPrimeAdminPanel:PrepareScript(ma_waterwalkoffbutton              , Locale["tt_watewrwalkoffbutton"]        , function() WoWPrimeAdminPanelCommands.ToggleWaterwalk("off") end)
  WoWPrimeAdminPanel:PrepareScript(ma_cheatcasttimeonbutton           , Locale["tt_cheatcasttimeonbutton"]      , function() WoWPrimeAdminPanelCommands.ToggleCheatCastTime("on") end)
  WoWPrimeAdminPanel:PrepareScript(ma_cheatcasttimeoffbutton          , Locale["tt_cheatcasttimeoffbutton"]     , function() WoWPrimeAdminPanelCommands.ToggleCheatCastTime("off") end)
  WoWPrimeAdminPanel:PrepareScript(ma_cheatcooldownonbutton           , Locale["tt_cheatcooldownonbutton"]      , function() WoWPrimeAdminPanelCommands.ToggleCheatCooldown("on") end)
  WoWPrimeAdminPanel:PrepareScript(ma_cheatcooldownoffbutton          , Locale["tt_cheatcooldownoffbutton"]     , function() WoWPrimeAdminPanelCommands.ToggleCheatCooldown("off") end)
  WoWPrimeAdminPanel:PrepareScript(ma_cheatgodonbutton                , Locale["tt_cheatgodonbutton"]           , function() WoWPrimeAdminPanelCommands.ToggleCheatGod("on") end)
  WoWPrimeAdminPanel:PrepareScript(ma_cheatgodoffbutton               , Locale["tt_cheatgodoffbutton"]          , function() WoWPrimeAdminPanelCommands.ToggleCheatGod("off") end)
  WoWPrimeAdminPanel:PrepareScript(ma_cheatpoweronbutton              , Locale["tt_cheatpoweronbutton"]         , function() WoWPrimeAdminPanelCommands.ToggleCheatPower("on") end)
  WoWPrimeAdminPanel:PrepareScript(ma_cheatpoweroffbutton             , Locale["tt_cheatpoweroffbutton"]        , function() WoWPrimeAdminPanelCommands.ToggleCheatPower("off") end)
  WoWPrimeAdminPanel:PrepareScript(ma_cheatstatusbutton               , Locale["tt_cheatstatusbutton"]          , function() WoWPrimeAdminPanelCommands.CheatStatus() end)
  WoWPrimeAdminPanel:PrepareScript(ma_gmingamebutton                  , Locale["tt_gmingamebutton"]             , function() WoWPrimeAdminPanelCommands.GMInGame() end)
  WoWPrimeAdminPanel:PrepareScript(ma_gmlistbutton                    , Locale["tt_gmlistbutton"]               , function() WoWPrimeAdminPanelCommands.GMList() end)
  WoWPrimeAdminPanel:PrepareScript(ma_petcreatebutton                 , Locale["tt_petcreatebutton"]            , function() WoWPrimeAdminPanelCommands.PetCreate() end)
  WoWPrimeAdminPanel:PrepareScript(ma_petlearnbutton                  , Locale["tt_petlearnbutton"]             , function() WoWPrimeAdminPanelCommands.PetLearn() end)
  WoWPrimeAdminPanel:PrepareScript(ma_petunlearnbutton                , Locale["tt_petunlearnbutton"]           , function() WoWPrimeAdminPanelCommands.PetUnLearn() end)
  WoWPrimeAdminPanel:PrepareScript(ma_pettpbutton                     , Locale["tt_pettpbutton"]                , function() WoWPrimeAdminPanelCommands.PetTP() end)
  WoWPrimeAdminPanel:PrepareScript(ma_lookuptaxibutton                , Locale["tt_lookuptaxibutton"]           , function() WoWPrimeAdminPanelCommands.LookupTaxi() end)
  WoWPrimeAdminPanel:PrepareScript(ma_gotaxinodebutton                , Locale["tt_gotaxinodebutton"]           , function() WoWPrimeAdminPanelCommands.GoTaxiNode() end)
  WoWPrimeAdminPanel:PrepareScript(ma_gotriggerbutton                 , Locale["tt_gotriggerbutton"]            , function() WoWPrimeAdminPanelCommands.GoTrigger() end)
  WoWPrimeAdminPanel:PrepareScript(ma_goxybutton                      , Locale["tt_goxybutton"]                 , function() WoWPrimeAdminPanelCommands.GoXY() end)
  WoWPrimeAdminPanel:PrepareScript(ma_goxyzbutton                     , Locale["tt_goxyzbutton"]                , function() WoWPrimeAdminPanelCommands.GoXYZ() end)
  WoWPrimeAdminPanel:PrepareScript(ma_gozonexybutton                  , Locale["tt_gozonexybutton"]             , function() WoWPrimeAdminPanelCommands.GoZoneXY() end)
  WoWPrimeAdminPanel:PrepareScript(ma_lookupzonebutton                , Locale["tt_lookupzonebutton"]           , function() WoWPrimeAdminPanelCommands.LookupZone() end)
  WoWPrimeAdminPanel:PrepareScript(ma_castbutton                      , Locale["tt_castbutton"]                 , function() WoWPrimeAdminPanelCommands.Cast() end)
  WoWPrimeAdminPanel:PrepareScript(ma_castbackbutton                  , Locale["tt_castbackbutton"]             , function() WoWPrimeAdminPanelCommands.CastBack() end)
  WoWPrimeAdminPanel:PrepareScript(ma_castdistbutton                  , Locale["tt_castdistbutton"]             , function() WoWPrimeAdminPanelCommands.CastDist() end)
  WoWPrimeAdminPanel:PrepareScript(ma_castselfbutton                  , Locale["tt_castselfbutton"]             , function() WoWPrimeAdminPanelCommands.CastSelf() end)
  WoWPrimeAdminPanel:PrepareScript(ma_casttargetbutton                , Locale["tt_casttargetbutton"]           , function() WoWPrimeAdminPanelCommands.CastTarget() end)
  WoWPrimeAdminPanel:PrepareScript(ma_listitembutton                  , Locale["tt_listitembutton"]             , function() WoWPrimeAdminPanelCommands.ListItem() end)
  WoWPrimeAdminPanel:PrepareScript(ma_charlistdeletedbutton           , Locale["tt_charlistdeleted"]            , function() WoWPrimeAdminPanelCommands.CharListDeleted() end)
  WoWPrimeAdminPanel:PrepareScript(ma_chardeletedrestorebutton        , Locale["tt_chardeletedrestore"]         , function() WoWPrimeAdminPanelCommands.CharDeletedRestore() end)
  WoWPrimeAdminPanel:PrepareScript(ma_gmclearbutton                   , Locale["tt_gmclearbutton"]              , function() WoWPrimeAdminPanelCommands.GmClear() end)
  WoWPrimeAdminPanel:PrepareScript(ma_acctaddonbutton                 , Locale["tt_acctaddonbutton"]            , function() WoWPrimeAdminPanelCommands.AcctAddon() end)
  WoWPrimeAdminPanel:PrepareScript(ma_acctgmlvlbutton                 , Locale["tt_acctgmlvlbutton"]            , function() WoWPrimeAdminPanelCommands.AcctGMLvl() end)
  WoWPrimeAdminPanel:PrepareScript(ma_gmnotifybutton                  , Locale["tt_gmnotifybutton"]             , function() WoWPrimeAdminPanelCommands.GMNotify() end)
  WoWPrimeAdminPanel:PrepareScript(ma_acctchangebutton                , Locale["tt_acctchangebutton"]           , function() WoWPrimeAdminPanelCommands.AcctChange() end)
  WoWPrimeAdminPanel:PrepareScript(ma_teleaddbutton                   , Locale["tt_teleaddbutton"]              , function() WoWPrimeAdminPanelCommands.TeleAddButton() end)
  WoWPrimeAdminPanel:PrepareScript(ma_teledelbutton                   , Locale["tt_teledelbutton"]              , function() WoWPrimeAdminPanelCommands.TeleDelButton() end)
  WoWPrimeAdminPanel:PrepareScript(ma_speedsliderreset_button         , Locale["tt_SpeedSliderReset"]           , function() WoWPrimeAdminPanelCommands.ResetSpeed() end)
  WoWPrimeAdminPanel:PrepareScript(ma_scalesliderreset_button         , Locale["tt_ScaleSliderReset"]           , function() WoWPrimeAdminPanelCommands.ResetScale() end)

  -- Speed Slider
  ma_speedslider:SetOrientation("HORIZONTAL")
  ma_speedslider:SetMinMaxValues(.5, 30)
  ma_speedslider:SetValueStep(0.5)
  ma_speedslider:SetValue(1)
  ma_speedsliderText:SetText("Speed: 1.0")
  ma_speedslider:EnableMouseWheel(true)
  ma_speedslider:SetScript("OnMouseWheel", function(self, delta)
    local min, max = self:GetMinMaxValues()
    local newVal = self:GetValue() + (delta * 0.5)
    if newVal < min then newVal = min end
    if newVal > max then newVal = max end
    self:SetValue(newVal)
    WoWPrimeAdminPanelCommands.SetSpeed()
  end)
  -- Scale Slider
  ma_scaleslider:SetOrientation("HORIZONTAL")
  ma_scaleslider:SetMinMaxValues(0.1 , 10)
  ma_scaleslider:SetValueStep(0.1)
  ma_scaleslider:SetValue(1)
  ma_scalesliderText:SetText("Scale: 1.0")
  ma_scaleslider:EnableMouseWheel(true)
  ma_scaleslider:SetScript("OnMouseWheel", function(self, delta)
    local min, max = self:GetMinMaxValues()
    local newVal = self:GetValue() + (delta * 0.5)
    if newVal < min then newVal = min end
    if newVal > max then newVal = max end
    self:SetValue(newVal)
    WoWPrimeAdminPanelCommands.SetScale()
  end)

--[[Char Tab]]
  WoWPrimeAdminPanelCommands.InitModelFrame()
  WoWPrimeAdminPanel:PrepareScript(ma_modelrotatelbutton              , Locale["tt_RotateLeft"]                 , function() WoWPrimeAdminPanelCommands.ModelRotateLeft() end)
  WoWPrimeAdminPanel:PrepareScript(ma_modelrotaterbutton              , Locale["tt_RotateRight"]                , function() WoWPrimeAdminPanelCommands.ModelRotateRight() end)
  WoWPrimeAdminPanel:PrepareScript(ma_killbutton                      , Locale["tt_killbutton"]                 , function() WoWPrimeAdminPanelCommands.KillSomething() end)
  WoWPrimeAdminPanel:PrepareScript(ma_revivebutton                    , Locale["tt_reviveplayer"]               , function() WoWPrimeAdminPanelCommands.RevivePlayer() end)
  WoWPrimeAdminPanel:PrepareScript(ma_savebutton                      , Locale["tt_saveplayer"]                 , function() WoWPrimeAdminPanelCommands.SavePlayer() end)
  WoWPrimeAdminPanel:PrepareScript(ma_kickbutton                      , Locale["tt_KickButton"]                 , function() WoWPrimeAdminPanelCommands.KickPlayer() end)
  WoWPrimeAdminPanel:PrepareScript(ma_cooldownbutton                  , Locale["tt_CooldownButton"]             , function() WoWPrimeAdminPanelCommands.Cooldown() end)
  WoWPrimeAdminPanel:PrepareScript(ma_guidbutton                      , Locale["tt_GUIDButton"]                 , function() WoWPrimeAdminPanelCommands.ShowGUID() end)
  WoWPrimeAdminPanel:PrepareScript(ma_pinfobutton                     , Locale["tt_PinfoButton"]                , function() WoWPrimeAdminPanelCommands.Pinfo() end)
  WoWPrimeAdminPanel:PrepareScript(ma_distancebutton                  , Locale["tt_DistanceButton"]             , function() WoWPrimeAdminPanelCommands.Distance() end)
  WoWPrimeAdminPanel:PrepareScript(ma_recallbutton                    , Locale["tt_RecallButton"]               , function() WoWPrimeAdminPanelCommands.Recall() end)
  WoWPrimeAdminPanel:PrepareScript(ma_demorphbutton                   , Locale["tt_DemorphButton"]              , function() WoWPrimeAdminPanelCommands.Demorph() end)
  WoWPrimeAdminPanel:PrepareScript(ma_gpsbutton                       , Locale["tt_GPSButton"]                  , function() WoWPrimeAdminPanelCommands.GPS() end)
  WoWPrimeAdminPanel:PrepareScript(ma_learnlangbutton                 , Locale["tt_learnlangbutton"]            , function() WoWPrimeAdminPanelCommands.LearnSpell(UIDropDownMenu_GetSelectedValue(ma_learnlangdropdown)) end)
  WoWPrimeAdminPanel:PrepareScript(ma_modifybutton                    , Locale["tt_modifybutton"]               , function() WoWPrimeAdminPanelCommands.Modify(UIDropDownMenu_GetSelectedValue(ma_modifydropdown),ma_modifyeditbox:GetText()) end)
  WoWPrimeAdminPanel:PrepareScript(ma_resetbutton                     , Locale["tt_resetbutton"]                , function() WoWPrimeAdminPanelCommands.Reset(UIDropDownMenu_GetSelectedValue(ma_resetdropdown)) end)
  WoWPrimeAdminPanel:PrepareScript(ma_modelzoominbutton               , Locale["tt_modelzoominbutton"]          , function() WoWPrimeAdminPanelCommands.CharModelZoomIn() end)
  WoWPrimeAdminPanel:PrepareScript(ma_modelzoomoutbutton              , Locale["tt_modelzoomoutbutton"]         , function() WoWPrimeAdminPanelCommands.CharModelZoomOut() end)
  WoWPrimeAdminPanel:PrepareScript(ma_charbindsight                   , Locale["tt_charbindsight"]              , function() WoWPrimeAdminPanelCommands.CharBindSight() end)
  WoWPrimeAdminPanel:PrepareScript(ma_charunbindsight                 , Locale["tt_charunbindsight"]            , function() WoWPrimeAdminPanelCommands.CharUnBindSight() end)
  WoWPrimeAdminPanel:PrepareScript(ma_charrenamebutton                , Locale["tt_charrename"]                 , function() WoWPrimeAdminPanelCommands.CharRename() end)
  WoWPrimeAdminPanel:PrepareScript(ma_charcustomizebutton             , Locale["tt_charcustomize"]              , function() WoWPrimeAdminPanelCommands.CharCustomize() end)
  WoWPrimeAdminPanel:PrepareScript(ma_charchangeracebutton            , Locale["tt_charchangerace"]             , function() WoWPrimeAdminPanelCommands.CharChangeRace() end)
  WoWPrimeAdminPanel:PrepareScript(ma_charchangefactionbutton         , Locale["tt_charchnagefaction"]          , function() WoWPrimeAdminPanelCommands.CharChangeFaction() end)
  WoWPrimeAdminPanel:PrepareScript(ma_charcombatstopbutton            , Locale["tt_charcombatstop"]             , function() WoWPrimeAdminPanelCommands.CharCombatStop() end)
  WoWPrimeAdminPanel:PrepareScript(ma_charmaxskillbutton              , Locale["tt_charmaxskill"]               , function() WoWPrimeAdminPanelCommands.CharMaxSkill() end)
  WoWPrimeAdminPanel:PrepareScript(ma_charfreezebutton                , Locale["tt_charfreeze"]                 , function() WoWPrimeAdminPanelCommands.CharFreeze() end)
  WoWPrimeAdminPanel:PrepareScript(ma_charunfreezebutton              , Locale["tt_charunfreeze"]               , function() WoWPrimeAdminPanelCommands.CharUnFreeze() end)
  WoWPrimeAdminPanel:PrepareScript(ma_charpossessbutton               , Locale["tt_charpossess"]                , function() WoWPrimeAdminPanelCommands.CharPossess() end)
  WoWPrimeAdminPanel:PrepareScript(ma_charunpossessbutton             , Locale["tt_charunpossess"]              , function() WoWPrimeAdminPanelCommands.CharUnPossess() end)
  WoWPrimeAdminPanel:PrepareScript(ma_charrepairitemsbutton           , Locale["tt_charrepair"]                 , function() WoWPrimeAdminPanelCommands.CharRepair() end)
  WoWPrimeAdminPanel:PrepareScript(ma_bankbutton                      , Locale["tt_BankButton"]                 , function() WoWPrimeAdminPanelCommands.ShowBank() end)
  WoWPrimeAdminPanel:PrepareScript(ma_checkbagbutton                  , Locale["tt_CheckBagButton"]             , function() WoWPrimeAdminPanelCommands.CheckBagButton() end)
  WoWPrimeAdminPanel:PrepareScript(ma_checkprofessionbutton            , Locale["tt_CheckProfessionButton"]      , function() WoWPrimeAdminPanelCommands.CheckProfessionButton() end)
  WoWPrimeAdminPanel:PrepareScript(ma_dismountbutton                  , Locale["tt_Dismount"]                   , function() WoWPrimeAdminPanelCommands.DismountPlayer() end)

  WoWPrimeAdminPanelCommands.LearnDropDownInitialize()
  UIDropDownMenu_Initialize(ma_learnlangdropdown , WoWPrimeAdminPanelCommands.LearnDropDownInitialize)
  UIDropDownMenu_SetWidth(ma_learnlangdropdown          , 80)
  UIDropDownMenu_SetButtonWidth(ma_learnlangdropdown    , 20)
  UIDropDownMenu_SetSelectedValue(ma_learnlangdropdown, "all_crafts")
  WoWPrimeAdminPanelCommands.ModifyDropDownInitialize()
  UIDropDownMenu_Initialize(ma_modifydropdown , WoWPrimeAdminPanelCommands.ModifyDropDownInitialize)
  UIDropDownMenu_SetWidth(ma_modifydropdown             , 80)
  UIDropDownMenu_SetButtonWidth(ma_modifydropdown       , 20)
  UIDropDownMenu_SetSelectedValue(ma_modifydropdown, "aspeed")
  WoWPrimeAdminPanelCommands.ResetDropDownInitialize()
  UIDropDownMenu_Initialize(ma_resetdropdown , WoWPrimeAdminPanelCommands.ResetDropDownInitialize)
  UIDropDownMenu_SetWidth(ma_resetdropdown              , 80)
  UIDropDownMenu_SetButtonWidth(ma_resetdropdown        , 20)
  UIDropDownMenu_SetSelectedValue(ma_resetdropdown, "honor")

  UIDropDownMenu_Initialize(ma_bandropdown , WoWPrimeAdminPanelCommands.BanDropDownInitialize)
  UIDropDownMenu_SetWidth(ma_bandropdown               , 80)
  UIDropDownMenu_SetButtonWidth(ma_bandropdown         , 20)
  UIDropDownMenu_SetSelectedValue(ma_bandropdown, "character")

  WoWPrimeAdminPanel:PrepareScript(ma_banbutton                       , Locale["tt_banbutton"]                  , function() WoWPrimeAdminPanelCommands.BanButton(UIDropDownMenu_GetSelectedValue(ma_bandropdown)) end)
  WoWPrimeAdminPanel:PrepareScript(ma_gonamebutton                    , Locale["tt_gonamebutton"]               , function() WoWPrimeAdminPanelCommands.GoNameButton() end)
  WoWPrimeAdminPanel:PrepareScript(ma_createguildbutton               , Locale["tt_createguildbutton"]          , function() WoWPrimeAdminPanelCommands.CreateGuildButton() end)
  WoWPrimeAdminPanel:PrepareScript(ma_baninfobutton                   , Locale["tt_baninfobutton"]              , function() WoWPrimeAdminPanelCommands.BanInfoButton(UIDropDownMenu_GetSelectedValue(ma_bandropdown)) end)
  WoWPrimeAdminPanel:PrepareScript(ma_groupgobutton                   , Locale["tt_groupgobutton"]              , function() WoWPrimeAdminPanelCommands.GroupGoButton() end)
  WoWPrimeAdminPanel:PrepareScript(ma_guildinvitebutton               , Locale["tt_guildinvitebutton"]          , function() WoWPrimeAdminPanelCommands.GuildInviteButton() end)
  WoWPrimeAdminPanel:PrepareScript(ma_banlistbutton                   , Locale["tt_banlistbutton"]              , function() WoWPrimeAdminPanelCommands.BanlistButton(UIDropDownMenu_GetSelectedValue(ma_bandropdown)) end)
  WoWPrimeAdminPanel:PrepareScript(ma_namegobutton                    , Locale["tt_namegobutton"]               , function() WoWPrimeAdminPanelCommands.NameGoButton() end)
  WoWPrimeAdminPanel:PrepareScript(ma_guildrankbutton                 , Locale["tt_guildrankbutton"]            , function() WoWPrimeAdminPanelCommands.GuildRankButton() end)
  WoWPrimeAdminPanel:PrepareScript(ma_telegroupbutton                 , Locale["tt_telegroupbutton"]            , function() WoWPrimeAdminPanelCommands.TeleGroupButton() end)
  WoWPrimeAdminPanel:PrepareScript(ma_unbanbutton                     , Locale["tt_unbanbutton"]                , function() WoWPrimeAdminPanelCommands.UnBanButton(UIDropDownMenu_GetSelectedValue(ma_bandropdown)) end)
  WoWPrimeAdminPanel:PrepareScript(ma_guilddeletebutton               , Locale["tt_guilddeletebutton"]          , function() WoWPrimeAdminPanelCommands.GuildDeleteButton() end)
  WoWPrimeAdminPanel:PrepareScript(ma_guilduninvitebutton             , Locale["tt_guilduninvitebutton"]        , function() WoWPrimeAdminPanelCommands.GuildUninviteButton() end)
  WoWPrimeAdminPanel:PrepareScript(ma_telenamebutton                  , Locale["tt_telenamebutton"]             , function() WoWPrimeAdminPanelCommands.TeleNameButton() end)
  WoWPrimeAdminPanel:PrepareScript(ma_mutebutton                      , Locale["tt_mutebutton"]                 , function() WoWPrimeAdminPanelCommands.MuteButton() end)
  WoWPrimeAdminPanel:PrepareScript(ma_charmorphbutton                 , Locale["tt_charmorphbutton"]            , function() WoWPrimeAdminPanelCommands.CharMorphButton() end)
  WoWPrimeAdminPanel:PrepareScript(ma_charaurabutton                  , Locale["tt_charaurabutton"]             , function() WoWPrimeAdminPanelCommands.CharAuraButton() end)
  WoWPrimeAdminPanel:PrepareScript(ma_charunaurabutton                , Locale["tt_charunaurabutton"]           , function() WoWPrimeAdminPanelCommands.CharUnAuraButton() end)
  WoWPrimeAdminPanel:PrepareScript(ma_jailabutton                     , Locale["tt_JailAButton"]                , function() WoWPrimeAdminPanelCommands.JailA() end)
  WoWPrimeAdminPanel:PrepareScript(ma_jailhbutton                     , Locale["tt_JailHButton"]                , function() WoWPrimeAdminPanelCommands.JailH() end)
  WoWPrimeAdminPanel:PrepareScript(ma_unjailbutton                    , Locale["tt_UnJailButton"]               , function() WoWPrimeAdminPanelCommands.UnJail() end)
  WoWPrimeAdminPanel:PrepareScript(ma_unmutebutton                    , Locale["tt_UnMuteButton"]               , function() WoWPrimeAdminPanelCommands.UnMuteButton() end)
  WoWPrimeAdminPanel:PrepareScript(ma_damagebutton                    , Locale["tt_DamageButton"]               , function() WoWPrimeAdminPanelCommands.DamageButton() end)
  WoWPrimeAdminPanel:PrepareScript(ma_hideareabutton                  , Locale["tt_HideAreaButton"]             , function() WoWPrimeAdminPanelCommands.HideAreaButton() end)
  WoWPrimeAdminPanel:PrepareScript(ma_showareabutton                  , Locale["tt_ShowAreaButton"]             , function() WoWPrimeAdminPanelCommands.ShowAreaButton() end)
  WoWPrimeAdminPanel:PrepareScript(ma_charclearbutton                 , Locale["tt_gmclearbutton"]              , function() WoWPrimeAdminPanelCommands.CharClearParams() end)

--[[NPC Tab]]
  WoWPrimeAdminPanelCommands.InitModelFrameNPC()
  WoWPrimeAdminPanel:PrepareScript(ma_npcmodelrotatelbutton           , Locale["tt_NPCRotateLeft"]              , function() WoWPrimeAdminPanelCommands.NpcModelRotateLeft() end)
  WoWPrimeAdminPanel:PrepareScript(ma_npcmodelrotaterbutton           , Locale["tt_NPCRotateRight"]             , function() WoWPrimeAdminPanelCommands.NpcModelRotateRight() end)
  WoWPrimeAdminPanel:PrepareScript(ma_npckillbutton                   , Locale["tt_NPCKillButton"]              , function() WoWPrimeAdminPanelCommands.NPCKillSomething() end)
  WoWPrimeAdminPanel:PrepareScript(ma_respawnbutton                   , Locale["tt_npcrespawn"]                 , function() WoWPrimeAdminPanelCommands.Respawn() end)
  WoWPrimeAdminPanel:PrepareScript(ma_npcdistancebutton               , Locale["tt_NPCDistanceButton"]          , function() WoWPrimeAdminPanelCommands.NPCDistance() end)
  WoWPrimeAdminPanel:PrepareScript(ma_NPCEntryIDButton                , Locale["tt_NPCEntryIDButton"]           , function() WoWPrimeAdminPanelCommands.NPCShowGUID() end)
  WoWPrimeAdminPanel:PrepareScript(ma_npcinfobutton                   , Locale["tt_NPCInfoButton"]              , function() WoWPrimeAdminPanelCommands.NPCInfo() end)
  WoWPrimeAdminPanel:PrepareScript(ma_npcdemorphbutton                , Locale["tt_NPCDemorph"]                 , function() WoWPrimeAdminPanelCommands.NPCDemorph() end)
  WoWPrimeAdminPanel:PrepareScript(ma_npcmovebutton                   , Locale["tt_NPCMove"]                    , function() WoWPrimeAdminPanelCommands.NPCMove() end)
  WoWPrimeAdminPanel:PrepareScript(ma_npcdelbutton                    , Locale["tt_NPCDel"]                     , function() WoWPrimeAdminPanelCommands.NPCDel() end)
  WoWPrimeAdminPanel:PrepareScript(ma_NPC_guidgetbutton               , Locale["tt_getguid"]                    , function() WoWPrimeAdminPanelCommands.NPC_GUID_Get() end)
  WoWPrimeAdminPanel:PrepareScript(ma_NPC_addbutton                   , Locale["tt_NPCAdd"]                     , function() WoWPrimeAdminPanelCommands.NPC_Add() end)
  WoWPrimeAdminPanel:PrepareScript(ma_NPC_addIDbutton                 , Locale["tt_NPCAddID"]                   , function() WoWPrimeAdminPanelCommands.NPC_AddID() end)
  WoWPrimeAdminPanel:PrepareScript(ma_npcgobutton                     , Locale["tt_NPCGo"]                      , function() WoWPrimeAdminPanelCommands.NPCGo() end)
  WoWPrimeAdminPanel:PrepareScript(ma_npcmorphbutton                  , Locale["tt_NPCMorph"]                   , function() WoWPrimeAdminPanelCommands.NPCMorph() end)
  WoWPrimeAdminPanel:PrepareScript(ma_npcsaybutton                    , Locale["tt_NPCSay"]                     , function() WoWPrimeAdminPanelCommands.NPCSay() end)
  WoWPrimeAdminPanel:PrepareScript(ma_npcyellbutton                   , Locale["tt_NPCYell"]                    , function() WoWPrimeAdminPanelCommands.NPCYell() end)
  WoWPrimeAdminPanel:PrepareScript(ma_npcaurabutton                   , Locale["tt_NPCAura"]                    , function() WoWPrimeAdminPanelCommands.NPCAura() end)
  WoWPrimeAdminPanel:PrepareScript(ma_npcunaurabutton                 , Locale["tt_NPCUnaura"]                  , function() WoWPrimeAdminPanelCommands.NPCUnaura() end)
  WoWPrimeAdminPanel:PrepareScript(ma_npcemotebutton                  , Locale["tt_PlayEmote"]                  , function() WoWPrimeAdminPanelCommands.NpcEmote(UIDropDownMenu_GetSelectedValue(ma_npcemotedropdown)) end)
  WoWPrimeAdminPanel:PrepareScript(ma_npcemotebutton_a                , Locale["tt_PlayEmote"]                  , function() WoWPrimeAdminPanelCommands.NpcEmote(UIDropDownMenu_GetSelectedValue(ma_npcemotedropdown_a)) end)
  WoWPrimeAdminPanel:PrepareScript(ma_npcdisplayupbutton              , Locale["tt_DisplayUp"]                  , function() WoWPrimeAdminPanelCommands.DisplayUP() end)
  WoWPrimeAdminPanel:PrepareScript(ma_npcdisplaydownbutton            , Locale["tt_DisplayDown"]                , function() WoWPrimeAdminPanelCommands.DisplayDown() end)
  WoWPrimeAdminPanel:PrepareScript(ma_npcID_UPbutton                  , Locale["tt_IDUp"]                       , function() WoWPrimeAdminPanelCommands.ID_UP() end)
  WoWPrimeAdminPanel:PrepareScript(ma_npcID_DOWNbutton                , Locale["tt_IDDown"]                     , function() WoWPrimeAdminPanelCommands.ID_DOWN() end)
  WoWPrimeAdminPanel:PrepareScript(ma_npcclearbutton                  , Locale["tt_NPCClear"]                   , function() WoWPrimeAdminPanelCommands.NPCClear() end)
  WoWPrimeAdminPanel:PrepareScript(ma_npcmodelzoominbutton            , Locale["tt_npcmodelzoominbutton"]       , function() WoWPrimeAdminPanelCommands.NPCModelZoomIn() end)
  WoWPrimeAdminPanel:PrepareScript(ma_npcmodelzoomoutbutton           , Locale["tt_npcmodelzoomoutbutton"]      , function() WoWPrimeAdminPanelCommands.NPCModelZoomOut() end)
  WoWPrimeAdminPanel:PrepareScript(ma_npcbindsight                    , Locale["tt_npcbindsight"]               , function() WoWPrimeAdminPanelCommands.NPCBindSight() end)
  WoWPrimeAdminPanel:PrepareScript(ma_npcunbindsight                  , Locale["tt_npcunbindsight"]             , function() WoWPrimeAdminPanelCommands.NPCUnBindSight() end)
  WoWPrimeAdminPanel:PrepareScript(ma_npccometomebutton               , Locale["tt_npccometome"]                , function() WoWPrimeAdminPanelCommands.NPCComeToMe() end)
  WoWPrimeAdminPanel:PrepareScript(ma_npcpossessbutton                , Locale["tt_npcpossess"]                 , function() WoWPrimeAdminPanelCommands.NPCPossess() end)
  WoWPrimeAdminPanel:PrepareScript(ma_npcunpossessbutton              , Locale["tt_npcunpossess"]               , function() WoWPrimeAdminPanelCommands.NPCUnPossess() end)
  WoWPrimeAdminPanel:PrepareScript(ma_npcfreezebutton                 , Locale["tt_NPCFreezeButton"]            , function() WoWPrimeAdminPanelCommands.NPCFreeze() end)
  WoWPrimeAdminPanel:PrepareScript(ma_npcfreezedelbutton              , Locale["tt_NPCFreezeDelButton"]         , function() WoWPrimeAdminPanelCommands.NPCFreezeDEL() end)
  WoWPrimeAdminPanel:PrepareScript(ma_npcclearparamsbutton            , Locale["tt_gmclearbutton"]              , function() WoWPrimeAdminPanelCommands.NpcClearParams() end)
  WoWPrimeAdminPanel:PrepareScript(ma_way_endaddbutton                , Locale["tt_WayEndAdd"]                  , function() WoWPrimeAdminPanelCommands.WayEndAdd() end)
  WoWPrimeAdminPanel:PrepareScript(ma_npcunfreeze_addwaybutton        , Locale["tt_NPCAddWay"]                  , function() WoWPrimeAdminPanelCommands.NPCAdd_Way() end)
  WoWPrimeAdminPanel:PrepareScript(ma_way_modifyaddbutton             , Locale["tt_WayMAdd"]                    , function() WoWPrimeAdminPanelCommands.WayModifyAdd() end)
  WoWPrimeAdminPanel:PrepareScript(ma_way_modifydelbutton             , Locale["tt_WayModifyDel"]               , function() WoWPrimeAdminPanelCommands.WayModifyDel() end)
  WoWPrimeAdminPanel:PrepareScript(ma_way_showonbutton                , Locale["tt_WayShow1"]                   , function() WoWPrimeAdminPanelCommands.WayShowOn() end)
  WoWPrimeAdminPanel:PrepareScript(ma_way_showoffbutton               , Locale["tt_WayShow0"]                   , function() WoWPrimeAdminPanelCommands.WayShowOff() end)
  WoWPrimeAdminPanel:PrepareScript(ma_npcunfreeze_addway_showonbutton , Locale["tt_NPCAdd_WayShowOn"]           , function() WoWPrimeAdminPanelCommands.NPCAdd_WayShowOn() end)
  WoWPrimeAdminPanel:PrepareScript(ma_npcunfreeze_waybutton           , Locale["tt_NPCUnFreeze_WayButton"]      , function() WoWPrimeAdminPanelCommands.NPCUnFreeze_Way() end)
  WoWPrimeAdminPanel:PrepareScript(ma_npcunfreeze_randombutton        , Locale["tt_NPCUnFreeze_RandomButton"]   , function() WoWPrimeAdminPanelCommands.NPCUnFreeze_Random() end)
  WoWPrimeAdminPanel:PrepareScript(ma_movestackbutton                 , Locale["tt_MoveStackButton"]            , function() WoWPrimeAdminPanelCommands.ShowMove() end)

--[[Gob Tab]]
  WoWPrimeAdminPanel:PrepareScript(ma_objgobutton                     , Locale["tt_ObjGo"]                      , function() WoWPrimeAdminPanelCommands.OBJGo() end)
  WoWPrimeAdminPanel:PrepareScript(ma_objaddbutton                    , Locale["tt_ObjAdd"]                     , function() WoWPrimeAdminPanelCommands.OBJAdd() end)
  WoWPrimeAdminPanel:PrepareScript(ma_objmovebutton                   , Locale["tt_ObjMove"]                    , function() WoWPrimeAdminPanelCommands.OBJMove() end)
  WoWPrimeAdminPanel:PrepareScript(ma_objturnbutton                   , Locale["tt_ObjTurn"]                    , function() WoWPrimeAdminPanelCommands.OBJTurn() end)
  WoWPrimeAdminPanel:PrepareScript(ma_objdelbutton                    , Locale["tt_ObjDel"]                     , function() WoWPrimeAdminPanelCommands.OBJDel() end)
  WoWPrimeAdminPanel:PrepareScript(ma_objnearbutton                   , Locale["tt_ObjNear"]                    , function() WoWPrimeAdminPanelCommands.OBJNear() end)
  WoWPrimeAdminPanel:PrepareScript(ma_objtargetbutton                 , Locale["tt_ObjTarget"]                  , function() WoWPrimeAdminPanelCommands.OBJTarget() end)
  WoWPrimeAdminPanel:PrepareScript(ma_gobactivatebutton               , Locale["tt_ObjActivate"]                , function() WoWPrimeAdminPanelCommands.OBJActivate() end)
  WoWPrimeAdminPanel:PrepareScript(ma_gobaddtempbutton                , Locale["tt_ObjAddTemp"]                 , function() WoWPrimeAdminPanelCommands.OBJAddTemp() end)
  WoWPrimeAdminPanel:PrepareScript(ma_gobinfobutton                   , Locale["tt_ObjInfo"]                    , function() WoWPrimeAdminPanelCommands.OBJInfo() end)
  WoWPrimeAdminPanel:PrepareScript(ma_gobclearinfobutton              , Locale["tt_ObjClearInfo"]               , function() WoWPrimeAdminPanelCommands.OBJClearInfo() end)
  WoWPrimeAdminPanel:PrepareScript(ma_gobsetphasebutton               , Locale["tt_ObjSetPhase"]                , function() WoWPrimeAdminPanelCommands.OBJSetPhase() end)
  WoWPrimeAdminPanel:PrepareScript(ma_gobshowmodel                    , Locale["tt_ObjShowModel"]               , function() WoWPrimeAdminPanelCommands.LoadAndShowGobModel() end)
  WoWPrimeAdminPanel:PrepareScript(ma_gobunloadmodel                  , Locale["tt_ObjUnloadModel"]             , function() WoWPrimeAdminPanelCommands.UnloadModels() end)
  WoWPrimeAdminPanelCommands.InitGobModelFrame()
  WoWPrimeAdminPanelCommands.InitGobButtonStates()
  WoWPrimeAdminPanel:PrepareScript(ma_gobmodelrotatelbutton           , Locale["tt_ObjRotateLeft"]              , function() WoWPrimeAdminPanelCommands.GobModelRotateLeft() end)
  WoWPrimeAdminPanel:PrepareScript(ma_gobmodelrotaterbutton           , Locale["tt_ObjRotateRight"]             , function() WoWPrimeAdminPanelCommands.GobModelRotateRight() end)
  WoWPrimeAdminPanel:PrepareScript(ma_gobmodelzoominbutton            , Locale["tt_ObjModelzoominbutton"]       , function() WoWPrimeAdminPanelCommands.GobModelZoomIn() end)
  WoWPrimeAdminPanel:PrepareScript(ma_gobmodelzoomoutbutton           , Locale["tt_ObjModelzoomoutbutton"]      , function() WoWPrimeAdminPanelCommands.GobModelZoomOut() end)
  WoWPrimeAdminPanel:PrepareScript(ma_gobmoveforwardbutton            , Locale["tt_ObjMoveForward"]             , function() WoWPrimeAdminPanelCommands.DMFront() end)
  WoWPrimeAdminPanel:PrepareScript(ma_gobmovebackbutton               , Locale["tt_ObjMoveBack"]                , function() WoWPrimeAdminPanelCommands.DMBack() end)
  WoWPrimeAdminPanel:PrepareScript(ma_gobmoveleftbutton               , Locale["tt_ObjMoveLeft"]                , function() WoWPrimeAdminPanelCommands.DMLeft() end)
  WoWPrimeAdminPanel:PrepareScript(ma_gobmoverightbutton              , Locale["tt_ObjMoveRight"]               , function() WoWPrimeAdminPanelCommands.DMRight() end)
  WoWPrimeAdminPanel:PrepareScript(ma_gobmoveupbutton                 , Locale["tt_ObjMoveUp"]                  , function() WoWPrimeAdminPanelCommands.DMUP() end)
  WoWPrimeAdminPanel:PrepareScript(ma_gobmovedownbutton               , Locale["tt_ObjMoveDown"]                , function() WoWPrimeAdminPanelCommands.DMDown() end)
  WoWPrimeAdminPanel:PrepareScript(ma_gobspawnherebutton              , Locale["tt_ObjSpawnHere"]               , function() WoWPrimeAdminPanelCommands.DMSS2() end)
  WoWPrimeAdminPanel:PrepareScript(ma_spawnonmovecheck                , nil                                     , function() WoWPrimeAdminPanelCommands.CheckToggle("spawn") end)
  WoWPrimeAdminPanel:PrepareScript(ma_moveonmovecheck                 , nil                                     , function() WoWPrimeAdminPanelCommands.CheckToggle("move") end)

--[[Tele Tab]]
  WoWPrimeAdminPanel:PrepareScript(ma_ContScrollBarEntry1             , nil                                     , function() WoWPrimeAdminPanel.db.char.selectedCont = "EK_N"; cont=WoWPrimeAdminPanel.db.char.selectedCont; WoWPrimeAdminPanelCommands.TeleScrollUpdate() end)
  WoWPrimeAdminPanel:PrepareScript(ma_ContScrollBarEntry2             , nil                                     , function() WoWPrimeAdminPanel.db.char.selectedCont = "EK_S"; cont=WoWPrimeAdminPanel.db.char.selectedCont; WoWPrimeAdminPanelCommands.TeleScrollUpdate() end)
  WoWPrimeAdminPanel:PrepareScript(ma_ContScrollBarEntry3             , nil                                     , function() WoWPrimeAdminPanel.db.char.selectedCont = "K"; cont=WoWPrimeAdminPanel.db.char.selectedCont; WoWPrimeAdminPanelCommands.TeleScrollUpdate() end)
  WoWPrimeAdminPanel:PrepareScript(ma_ContScrollBarEntry4             , nil                                     , function() WoWPrimeAdminPanel.db.char.selectedCont = "Ou"; cont=WoWPrimeAdminPanel.db.char.selectedCont; WoWPrimeAdminPanelCommands.TeleScrollUpdate() end)
  WoWPrimeAdminPanel:PrepareScript(ma_ContScrollBarEntry5             , nil                                     , function() WoWPrimeAdminPanel.db.char.selectedCont = "N_A"; cont=WoWPrimeAdminPanel.db.char.selectedCont; WoWPrimeAdminPanelCommands.TeleScrollUpdate() end)
  WoWPrimeAdminPanel:PrepareScript(ma_ContScrollBarEntry6             , nil                                     , function() WoWPrimeAdminPanel.db.char.selectedCont = "N_H"; cont=WoWPrimeAdminPanel.db.char.selectedCont; WoWPrimeAdminPanelCommands.TeleScrollUpdate() end)
  WoWPrimeAdminPanel:PrepareScript(ma_ContScrollBarEntry7             , nil                                     , function() WoWPrimeAdminPanel.db.char.selectedCont = "BG"; cont=WoWPrimeAdminPanel.db.char.selectedCont; WoWPrimeAdminPanelCommands.TeleScrollUpdate() end)
  WoWPrimeAdminPanel:PrepareScript(ma_ContScrollBarEntry8             , nil                                     , function() WoWPrimeAdminPanel.db.char.selectedCont = "I_EK"; cont=WoWPrimeAdminPanel.db.char.selectedCont; WoWPrimeAdminPanelCommands.TeleScrollUpdate() end)
  WoWPrimeAdminPanel:PrepareScript(ma_ContScrollBarEntry9             , nil                                     , function() WoWPrimeAdminPanel.db.char.selectedCont = "I_K"; cont=WoWPrimeAdminPanel.db.char.selectedCont; WoWPrimeAdminPanelCommands.TeleScrollUpdate() end)
  WoWPrimeAdminPanel:PrepareScript(ma_ContScrollBarEntry10            , nil                                     , function() WoWPrimeAdminPanel.db.char.selectedCont = "I_O"; cont=WoWPrimeAdminPanel.db.char.selectedCont; WoWPrimeAdminPanelCommands.TeleScrollUpdate() end)
  WoWPrimeAdminPanel:PrepareScript(ma_ContScrollBarEntry11            , nil                                     , function() WoWPrimeAdminPanel.db.char.selectedCont = "I_N"; cont=WoWPrimeAdminPanel.db.char.selectedCont; WoWPrimeAdminPanelCommands.TeleScrollUpdate() end)
  WoWPrimeAdminPanel:PrepareScript(ma_ContScrollBarEntry12            , nil                                     , function() WoWPrimeAdminPanel.db.char.selectedCont = "OT"; cont=WoWPrimeAdminPanel.db.char.selectedCont; WoWPrimeAdminPanelCommands.TeleScrollUpdate() end)

--[[Tickets Tab]]
  WoWPrimeAdminPanel:PrepareScript(ma_tabbutton_ticket                , Locale["tt_TicketButton"]               , function() WoWPrimeAdminPanelCommands.ShowTicketTab() end)
  WoWPrimeAdminPanel:PrepareScript(ma_resetticketsbutton              , Locale["tt_LoadTickets"]                , function() WoWPrimeAdminPanelCommands.RefreshTickets() end)
  WoWPrimeAdminPanel:PrepareScript(ma_deleteticketbutton              , Locale["tt_DeleteTicket"]               , function() WoWPrimeAdminPanelCommands.Ticket("delete") end)
  WoWPrimeAdminPanel:PrepareScript(ma_answerticketbutton              , Locale["tt_AnswerTicket"]               , function() WoWPrimeAdminPanelCommands.Ticket("answer") end)
  WoWPrimeAdminPanel:PrepareScript(ma_getcharticketbutton             , Locale["tt_GetCharTicket"]              , function() WoWPrimeAdminPanelCommands.Ticket("getchar") end)
  WoWPrimeAdminPanel:PrepareScript(ma_gocharticketbutton              , Locale["tt_GoCharTicket"]               , function() WoWPrimeAdminPanelCommands.Ticket("gochar") end)
  WoWPrimeAdminPanel:PrepareScript(ma_whisperticketbutton             , Locale["tt_WhisperTicket"]              , function() WoWPrimeAdminPanelCommands.Ticket("whisper") end)
  WoWPrimeAdminPanel:PrepareScript(ma_goticketbutton                  , Locale["tt_GoTicket"]                   , function() WoWPrimeAdminPanelCommands.Ticket("goticket") end)

--[[Misc Tab]]
  WoWPrimeAdminPanel:PrepareScript(ma_checktransparencybutton         , nil                                     , function() WoWPrimeAdminPanelCommands.ToggleTransparencyCheckbox() end)
  WoWPrimeAdminPanel:PrepareScript(ma_checklocalsearchstringsbutton   , nil                                     , function() WoWPrimeAdminPanelCommands.ToggleLocalSearchStringsCheckbox() end)
  WoWPrimeAdminPanel:PrepareScript(ma_showchatoutputbutton            , nil                                     , function() WoWPrimeAdminPanelCommands.ToggleShowChatOutputCheckbox() end)
  WoWPrimeAdminPanel:PrepareScript(ma_showminimapbutton               , nil                                     , function() WoWPrimeAdminPanelCommands.ToggleMinimapButtonCheckbox() end)
  WoWPrimeAdminPanel:PrepareScript(ma_bgcolorshowbutton               , nil                                     , function() WoWPrimeAdminPanelCommands.ShowColorPicker("bg") end)
  WoWPrimeAdminPanel:PrepareScript(ma_frmcolorshowbutton              , nil                                     , function() WoWPrimeAdminPanelCommands.ShowColorPicker("frm") end)
  WoWPrimeAdminPanel:PrepareScript(ma_btncolorshowbutton              , nil                                     , function() WoWPrimeAdminPanelCommands.ShowColorPicker("btn") end)
  WoWPrimeAdminPanel:PrepareScript(ma_linkifiercolorbutton            , nil                                     , function() WoWPrimeAdminPanelCommands.ShowColorPicker("linkifier") end)
  WoWPrimeAdminPanel:PrepareScript(ma_showminimenubutton              , nil                                     , function() WoWPrimeAdminPanelCommands.ToggleMinimenuCheckbox() end)
  WoWPrimeAdminPanel:PrepareScript(ma_showtooltipsbutton              , nil                                     , function() WoWPrimeAdminPanelCommands.ToggleTooltipsCheckbox() end)
  WoWPrimeAdminPanel:PrepareScript(ma_instantteleportbutton           , nil                                     , function() WoWPrimeAdminPanelCommands.ToggleInstantTeleport() end)
  WoWPrimeAdminPanel:PrepareScript(ma_updatechangesbutton             , Locale["tt_updatechanges"]              , function() WoWPrimeAdminPanelCommands.UpdateChanges() end)
  WoWPrimeAdminPanel:PrepareScript(ma_ApplyWeatherButton              , Locale["tt_ApplyWeatherButton"]         , function() WoWPrimeAdminPanelCommands.ChangeWeather(UIDropDownMenu_GetSelectedValue(ma_weatherdropdown)) end)

--[[Server Tab]]
  WoWPrimeAdminPanel:PrepareScript(ma_announcebutton                  , Locale["tt_AnnounceButton"]             , function() WoWPrimeAdminPanelCommands.Announce(ma_announceeditbox:GetText()) end)
  WoWPrimeAdminPanel:PrepareScript(ma_resetannouncebutton             , nil                                     , function() ma_announceeditbox:SetText("") end)
  WoWPrimeAdminPanel:PrepareScript(ma_restartbutton                   , Locale["tt_RestartButton"]              , function() WoWPrimeAdminPanelCommands.Restart(ma_shutdowneditbox:GetText()) end)
  WoWPrimeAdminPanel:PrepareScript(ma_shutdownbutton                  , Locale["tt_ShutdownButton"]             , function() WoWPrimeAdminPanelCommands.Shutdown(ma_shutdowneditbox:GetText()) end)
  WoWPrimeAdminPanel:PrepareScript(ma_cancelshutdownbutton            , Locale["tt_CancelShutdownButton"]       , function() WoWPrimeAdminPanelCommands.CancelShutdown() end)
  WoWPrimeAdminPanel:PrepareScript(ma_loadtablebutton                 , Locale["tt_ReloadTableButton"]          , function() WoWPrimeAdminPanelCommands.ReloadTable(UIDropDownMenu_GetSelectedValue(ma_reloadtabledropdown)) end)
  WoWPrimeAdminPanel:PrepareScript(ma_loadscriptsbutton               , Locale["tt_ReloadScriptsButton"]        , function() WoWPrimeAdminPanelCommands.ReloadScripts() end)
  WoWPrimeAdminPanel:PrepareScript(ma_updatedelaybutton               , nil                                     , function()
    if ma_delayparam then
      WoWPrimeAdminPanel.db.profile.style.delayparam = ma_delayparam:GetText()
      WoWPrimeAdminPanel:Print("Update frequency saved: " .. ma_delayparam:GetText())
    end
  end)

--[[Log Tab]]
end
